name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant permission
        run: chmod +x ./gradlew

      - name: Generate coverage report
        run: ./gradlew :jhu-seclab-cobra-externs-phpstubs:test :jhu-seclab-cobra-externs-phpstubs:koverXmlReport

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./externs-phpstubs/build/reports/kover/report.xml
