package edu.jhu.cobra.externs.phpstubs

import edu.jhu.cobra.commons.phpmodels.ArgPattern
import edu.jhu.cobra.commons.phpmodels.DocumentSetLoader
import edu.jhu.cobra.commons.phpmodels.FunctionSubject
import edu.jhu.cobra.commons.phpmodels.ModelEntry
import edu.jhu.cobra.commons.phpmodels.ModelSubject
import edu.jhu.cobra.commons.phpmodels.Port
import edu.jhu.cobra.commons.phpmodels.Propagation
import edu.jhu.cobra.commons.phpmodels.ReturnKind
import edu.jhu.cobra.commons.phpmodels.ValueSemantics
import edu.jhu.cobra.commons.phpmodels.Verification
import edu.jhu.cobra.commons.value.BoolVal
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * Tests for the hand-maintained value rules set rooted at [StubResources.VALUE_RULES].
 *
 * - `value rules set loads without a vocabulary` — verifies the set names no category or color
 * - `value rules set is manually verified` — verifies the set's provenance
 * - `every value rules entry is an unsigned entry asserting only the value unit` — verifies the shape rule
 * - `every value rules subject is a generated declaration` — verifies existence in the generated set
 * - `no value rules unit repeats the generated unit` — verifies each unconditional unit differs from the generated one
 * - `mode-switching subjects carry a conditional entry and an unconditional one` — verifies print_r and var_export
 * - `representative units follow the PHP manual` — verifies typed results and flow sets
 */
internal class ValueRulesSetTest {
    private val rules by lazy { DocumentSetLoader.load(StubResources.opener(StubResources.VALUE_RULES)) }
    private val generated by lazy { DocumentSetLoader.load(StubResources.opener(StubResources.MODELS)) }
    private val unconditional: Map<ModelSubject, ModelEntry> by lazy {
        rules.entries.filter { it.condition == null }.associateBy { it.subject }
    }

    @Test
    fun `value rules set loads without a vocabulary`() {
        assertTrue(rules.entries.isNotEmpty())
        assertTrue(rules.vocabulary.vulnClasses.isEmpty())
        assertTrue(rules.vocabulary.origins.isEmpty())
        assertTrue(rules.policy.isEmpty())
    }

    @Test
    fun `value rules set is manually verified`() {
        assertEquals(Verification.MANUAL, assertNotNull(rules.provenance).verification)
    }

    @Test
    fun `every value rules entry is an unsigned entry asserting only the value unit`() {
        for (entry in rules.entries) {
            assertNull(entry.signature, "${entry.subject}")
            assertNotNull(entry.body.returns, "${entry.subject}")
            assertNull(entry.body.sources, "${entry.subject}")
            assertNull(entry.body.sinks, "${entry.subject}")
            assertNull(entry.body.sanitizers, "${entry.subject}")
        }
    }

    @Test
    fun `every value rules subject is a generated declaration`() {
        val declared = generated.entries.map { it.subject }.toSet()
        val missing = rules.entries.map { it.subject }.filter { it !in declared }
        assertTrue(missing.isEmpty(), "Subjects absent from the generated set: $missing")
    }

    @Test
    fun `no value rules unit repeats the generated unit`() {
        val units = generated.entries.associate { it.subject to it.body.valueSemantics() }
        for ((subject, entry) in unconditional) {
            assertNotEquals(units.getValue(subject), entry.body.valueSemantics(), "$subject")
        }
    }

    @Test
    fun `mode-switching subjects carry a conditional entry and an unconditional one`() {
        for (name in listOf("print_r", "var_export")) {
            val branches = rules.entries.filter { it.subject == FunctionSubject(name) }
            assertEquals(2, branches.size, name)
            val conditional = branches.single { it.condition != null }
            assertEquals(ArgPattern(listOf(null, BoolVal(true))), conditional.condition)
            assertEquals(ValueSemantics(ReturnKind.STR, listOf(argumentToReturn(0))), conditional.body.valueSemantics())
            assertNull(branches.single { it.condition == null }.body.propagation, name)
        }
    }

    @Test
    fun `representative units follow the PHP manual`() {
        assertEquals(ValueSemantics(ReturnKind.NUM, listOf(argumentToReturn(0))), unitOf("strlen"))
        assertEquals(ValueSemantics(ReturnKind.STR, emptyList()), unitOf("getenv"))
        assertEquals(ValueSemantics(ReturnKind.STR, listOf(argumentToReturn(0))), unitOf("strstr"))
        assertEquals(ValueSemantics(ReturnKind.NUM, emptyList()), unitOf("print"))
        assertEquals(
            ValueSemantics(ReturnKind.ANY, listOf(Propagation(from = Port.Argument(0), to = Port.Argument(1)))),
            unitOf("parse_str"),
        )
        assertNull(unconditional[FunctionSubject("crypt")])
        assertNull(unconditional[FunctionSubject("str_increment")])
    }

    private fun unitOf(name: String): ValueSemantics = unconditional.getValue(FunctionSubject(name)).body.valueSemantics()!!

    private fun argumentToReturn(position: Int): Propagation = Propagation(from = Port.Argument(position), to = Port.Return)
}
